[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "secret-triage"
version = "0.1.2"
description = "Post-procesador de informes Gitleaks con LLM local (Ollama)"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Ángela Ramírez Barajas" }]
keywords = ["gitleaks", "secrets", "llm", "ollama", "devsecops"]
dependencies = [
  "PyYAML>=6.0.1",
  "requests>=2.31.0",
]

[project.urls]
Homepage = "https://github.com/aramirezbarajas/secret-scan-tfm/tree/main/secret-triage"
Repository = "https://github.com/aramirezbarajas/secret-scan-tfm"

[project.optional-dependencies]
dev = ["pytest>=7.0", "build>=1.0", "twine>=5.0"]

[project.scripts]
secret-triage = "secret_triage.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
secret_triage = ["default.yaml"]
